### ISSUE TITLE
[BE] iOS클래스와 회의 사전 준비

### ISSUE THREAD

**Issue by ghost** [okstring/todo-list#6]
iOS분들과 협업을 위한 질문 사항들.

1. 어떤 기능이 필요하고 그 기능에 따라 어떤 클래스나 필드가 필요한지 상의
2. Mockup API에 대한 제공 여부 확인
3. Data 전송이 없는 새로운 팝업창이 뜰 때 BE에서 해줄 것이 있는지 여부 확인 (ex: 새로운 카드 추가)
4. URL을 BE에서 정할지, 혹시 iOS에서 필요한 URL이 있는지 여부 확인 
5. Branch 관리 단위에 대해 상의

**Comment by bong6981** [comment]
카드 : 타이틀, 본문, Web/App, 시간(초단위) 
상태값 : 해야한일 - 하고있는일 - 완료
- 리스트
